services:
  - type: web
    name: my-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
